import { describe, it, expect } from "vitest";

import { SNIFF_BYTES, mayBeGenotypeType, sniffGenotypeHeader } from "./genotypeFormat.js";

// The same four layouts the backend's genotype_format tests use, so the
// browser and the server recognise one file the same way.
const WEGENE = [
  "# This data file generated by WeGene at: Mon, 23 Jun 2025 09:13:43",
  "#",
  "# rsid\tchromosome\tposition\tgenotype",
  "",
  "rs62635286\t1\t13116\tTT",
].join("\n");

const TWENTYTHREE = [
  ...Array.from({ length: 20 }, (_, i) => `# 23andMe comment line ${i}`),
  "# rsid\tchromosome\tposition\tgenotype",
  "rs4477212\t1\t82154\tAA",
].join("\n");

const ANCESTRY = [
  "#AncestryDNA raw data download",
  "rsid\tchromosome\tposition\tallele1\tallele2",
  "rs4988235\t2\t136608646\tC\tT",
].join("\n");

const MYHERITAGE = [
  "# MyHeritage DNA raw data.",
  "RSID,CHROMOSOME,POSITION,RESULT",
  '"rs429358","19","44908684","AG"',
].join("\n");

describe("sniffGenotypeHeader", () => {
  it("recognises WeGene, and not by its banner", () => {
    expect(sniffGenotypeHeader(WEGENE)).toBe("genotype");
    expect(sniffGenotypeHeader(WEGENE.replace("WeGene", "SomeoneElse"))).toBe("genotype");
  });

  it("recognises 23andMe, whose header is past the first line", () => {
    // The old check was `startsWith(<WeGene banner>)`.
    expect(TWENTYTHREE.indexOf("# rsid")).toBeGreaterThan(100);
    expect(sniffGenotypeHeader(TWENTYTHREE)).toBe("genotype");
  });

  it("recognises AncestryDNA's split alleles", () => {
    expect(sniffGenotypeHeader(ANCESTRY)).toBe("alleles");
  });

  it("recognises MyHeritage's quoted CSV", () => {
    expect(sniffGenotypeHeader(MYHERITAGE)).toBe("genotype");
  });

  it("tolerates a byte-order mark and CRLF line ends", () => {
    expect(sniffGenotypeHeader("\uFEFF" + MYHERITAGE.replace(/\n/g, "\r\n"))).toBe("genotype");
  });

  it.each([
    ["an empty file", ""],
    ["prose", "hello world\nthis is a note\n"],
    ["prose that names rs-numbers", "rs4988235 is the lactase SNP\nrs1801133 is MTHFR\n"],
    ["data rows with no header", "rs4988235\t2\t136608646\tCT\n"],
    ["a report that mentions a chromosome", "Patient: X\nchromosome analysis: normal\n"],
  ])("refuses %s", (_label, text) => {
    // Exempting any of these from the size cap would let an arbitrary large
    // text file through, and the server would then refuse it anyway.
    expect(sniffGenotypeHeader(text)).toBe(null);
  });

  it("decides within the sniff window, whatever follows", () => {
    const huge = WEGENE + "\n" + "rs1\t1\t1\tAA\n".repeat(50000);
    expect(huge.length).toBeGreaterThan(SNIFF_BYTES);
    expect(sniffGenotypeHeader(huge)).toBe("genotype");
  });
});

describe("mayBeGenotypeType", () => {
  it("lets through what a genotype export is served as", () => {
    for (const t of ["text/plain", "text/csv", "application/vnd.ms-excel", "", undefined]) {
      expect(mayBeGenotypeType(t)).toBe(true);
    }
  });

  it("does not read a PDF or a photo", () => {
    for (const t of ["application/pdf", "image/jpeg", "image/png"]) {
      expect(mayBeGenotypeType(t)).toBe(false);
    }
  });
});
